name: 'Build and install package'
description: 'Build and install python package'
inputs:
  package_file:
    description: 'Path to package setup python script.'
    required: false
    default: 'package_setup.py'
outputs:
  wheel-file:
    description: "Wheel filename"
    value: ${{ steps.wheel.outputs.wheel-file }}
runs:
  using: "composite"
  steps:
    - name: Install python pre-reqs
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine bump2version dataclasses
      shell: bash
    - name: Add IDM artifactory end-point to pip config
      run: python ./.github/scripts/update_pip_conf.py
      shell: bash
    - name: bumpversion
      run: bumpversion --allow-dirty --config-file .bump_version.cfg patch
      shell: bash
    - name: build wheel
      run: python ${{ inputs.package_file }} bdist_wheel
      shell: bash
    - id: wheel
      run: python ./.github/scripts/get_wheel_filename.py --package-file ${{ inputs.package_file }} --set-gh-actions-var wheel-file
      shell: bash
    - name: install package
      run: pip install ${{ steps.wheel.outputs.wheel-file }}
      shell: bash
    
