name: run sft tests
on:
  workflow_dispatch:

jobs:
  run-all-test-ubuntu-prod:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.9 ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Config github user
        run: |
          git config --global user.email "idm_bamboo_user@idmod.org"
          git config --global user.name "BambooUser-IDM"
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Build and install package
        uses: ./.github/actions/build-install-package
        with:
          package_file: 'package_setup.py'
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install idm-test package
        run: |
          pip install idm-test>=0.0.13 --extra-index-url https://packages.idmod.org/api/pypi/pypi-production/simple
      - name: Login to comps2
        run: |
          python ./.dev_scripts/create_auth_token_args.py --username "${{ secrets.COMPS_USER }}" --password "${{ secrets.COMPS_PASSWORD }}"
      - name: run tests
        run: |
          cd tests
          python run_all_sft_tests.py
      - name: Upload sft test result to artifactory
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: sft_test_results
          path: |
            **/test_results.xml

